name: Build and Push to ECR via EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      working-directory: ./core
      run: |
        docker build -t ${{ vars.DOCKERHUB_USERNAME }}/wan22:latest .
        docker push ${{ vars.DOCKERHUB_USERNAME }}/wan22:latest